name: Decision Record (ADR)
description: 意思決定を記録する（Architecture Decision Record）
title: "[ADR]: "
labels: ["decision", "documentation"]

body:
  - type: markdown
    attributes:
      value: |
        ## 意思決定ログ（ADR: Architecture Decision Record）
        重要な技術的・設計上の意思決定を記録し、将来の参照に役立てます。

        > **GitHubはコード管理ツールではなく、思考・責任・意思決定を構造化するOS**

  - type: input
    id: decision_date
    attributes:
      label: 決定日
      description: この決定が行われた日付
      placeholder: "2025-01-01"
    validations:
      required: true

  - type: dropdown
    id: status
    attributes:
      label: ステータス
      description: この決定の現在の状態
      options:
        - 提案中（Proposed）
        - 承認済（Accepted）
        - 非推奨（Deprecated）
        - 却下（Rejected）
        - 置換済（Superseded by ADR-xxx）
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: カテゴリ
      description: この決定が属する領域
      options:
        - アーキテクチャ
        - データベース設計
        - API設計
        - セキュリティ
        - インフラ/DevOps
        - UI/UX
        - パフォーマンス
        - 外部サービス連携
        - 開発プロセス
        - その他
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: 背景・状況（Context）
      description: |
        この決定が必要になった背景は何か？
        どのような問題・課題があったか？
      placeholder: |
        例: ユーザー数が急増し、現在のアーキテクチャでは
        レスポンスタイムが許容範囲を超えるようになった
    validations:
      required: true

  - type: textarea
    id: decision
    attributes:
      label: 決定内容（Decision）
      description: 何を決定したか？具体的に記載
      placeholder: |
        例: マイクロサービスアーキテクチャを採用し、
        認証サービスを分離する
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 検討した代替案（Alternatives Considered）
      description: |
        他にどのような選択肢を検討したか？
        それぞれのPros/Consを記載
      placeholder: |
        ### 案1: モノリスのままスケールアップ
        - Pros: 実装が簡単、既存知識で対応可能
        - Cons: 将来的なスケーラビリティに限界

        ### 案2: サーバーレス化
        - Pros: 運用コスト削減
        - Cons: ベンダーロックイン、コールドスタート問題
    validations:
      required: true

  - type: textarea
    id: why_rejected
    attributes:
      label: 代替案を却下した理由（Why Not）
      description: なぜ他の選択肢を採用しなかったか？
      placeholder: |
        案1は短期的には有効だが、1年後の想定ユーザー数では
        対応困難と判断。案2はベンダーロックインリスクが高すぎる。
    validations:
      required: true

  - type: textarea
    id: consequences
    attributes:
      label: 影響・結果（Consequences）
      description: |
        この決定によって生じるメリット・デメリット・リスク
      placeholder: |
        ### メリット
        - スケーラビリティ向上
        - チーム分割が容易に

        ### デメリット
        - 初期実装コスト増
        - 運用複雑性の増加

        ### リスク
        - サービス間通信の障害
        - データ整合性の担保
    validations:
      required: true

  - type: textarea
    id: open_questions
    attributes:
      label: 未解決事項（Open Questions）
      description: まだ決まっていないこと、今後検討が必要なこと
      placeholder: |
        - [ ] サービス間認証の方式（JWT vs mTLS）
        - [ ] ログ集約基盤の選定
        - [ ] 障害時のフォールバック戦略

  - type: textarea
    id: related
    attributes:
      label: 関連情報
      description: 関連するIssue、PR、ドキュメント、外部参照
      placeholder: |
        - 関連Issue: #123
        - 参考資料: https://...
        - 前提となるADR: #100

  - type: checkboxes
    id: checklist
    attributes:
      label: 確認事項
      options:
        - label: 関係者と議論・合意した
          required: true
        - label: 代替案を十分に検討した
          required: true
        - label: リスクと対策を評価した
